### ISSUE TITLE
thumbs not deleted after delete the image and when upload other file in type image is still upload

### ISSUE THREAD

**Issue by faza13** [tsawler/laravel-filemanager#23]
1.
i found some typo
in DeleteController at line 85
if (Session::get('lfm_type') == "Images'")
you have triple quote after image.

2.
when i upload other file in lfm_type == images its still uploaded and button upload always loading because an error
![loading](https://cloud.githubusercontent.com/assets/7368173/8393081/6d91f68c-1d29-11e5-915f-991ecb8150e6.png)

sorry for my bad english
thanks

**Comment by tsawler** [comment]
Many thanks for pointing this out. Fixed in release 0.5.2.

**Comment by tsawler** [comment]
Hmm... I missed what you were saying about uploading "other file type" in images. You mean you are trying to upload a non-image file where you would normally upload an image, and you are getting an error. I'll look into that as soon as I can.

**Comment by mortezazmudeh** [comment]
Hi, I am using Ckeditor and after adding the following script for file browse  it still does not show the brows button on the image tab what should i do.

**Comment by mortezazmudeh** [comment]
it does'n t show the content of a folder if there is any images
